language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libevent-2.0-5 libevent-dev libblas-dev libblas3gf gfortran liblapack-dev
install:
    - pip install -r requirements.txt --use-mirrors
    - python manage.py syncdb --migrate --noinput
    - git clone https://www.github.com/statsmodels/statsmodels
    - cd statsmodels && python setup.py build && python setup.py install
script: rake test
