language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libevent-2.0-5 libevent-dev
install:
    - pip install -r requirements.txt --use-mirrors
    - python manage.py syncdb --migrate --noinput
script: rake test
